/**
 * Relevamiento de papeleras de La Matanza, para sembrar el tablero de
 * prospección. Cada ficha salió de directorios comerciales y de los perfiles
 * públicos del propio comercio; la columna `fuente` dice de dónde.
 *
 * Los datos de un comercio chico envejecen rápido: un teléfono que no atiende o
 * una dirección vieja no son un error del relevamiento, son el motivo por el
 * que el tablero guarda `verificado`. Lo que se confirma llamando se corrige en
 * la ficha y queda marcado; esta lista no se vuelve a pisar sobre lo editado.
 *
 * Importante sobre `telefono`: se transcribe tal como lo publica la fuente. Los
 * que están incompletos —el directorio los muestra cortados— van con lo que hay
 * y una nota, en vez de completarlos a ojo.
 */

export type SemillaProspecto = {
  /** Slug estable: la reimportación reconoce por acá lo que ya está cargado. */
  id: string;
  comercio: string;
  localidad: string;
  direccion: string;
  telefono: string;
  whatsapp: string;
  email: string;
  web: string;
  instagram: string;
  facebook: string;
  horario: string;
  notas: string;
  fuente: string;
};

/**
 * Centro aproximado de cada localidad de La Matanza. Se usa para poner el pin
 * en el mapa mientras nadie geocodificó la dirección exacta: ubica el comercio
 * en su barrio, no en su puerta, y el tablero lo muestra como aproximado.
 */
export const CENTROS_LOCALIDAD: Record<string, { lat: number; lng: number }> = {
  "San Justo": { lat: -34.6769, lng: -58.5606 },
  "Ramos Mejía": { lat: -34.6432, lng: -58.5654 },
  "Lomas del Mirador": { lat: -34.6667, lng: -58.5236 },
  "Villa Madero": { lat: -34.6889, lng: -58.5075 },
  "La Tablada": { lat: -34.6833, lng: -58.5333 },
  "Isidro Casanova": { lat: -34.7017, lng: -58.5883 },
  "Villa Luzuriaga": { lat: -34.6742, lng: -58.5967 },
  "Rafael Castillo": { lat: -34.7167, lng: -58.6333 },
  "Gregorio de Laferrere": { lat: -34.75, lng: -58.5833 },
  "González Catán": { lat: -34.7833, lng: -58.65 },
  "Virrey del Pino": { lat: -34.85, lng: -58.6833 },
  Tapiales: { lat: -34.7, lng: -58.5 },
  "Aldo Bonzi": { lat: -34.7, lng: -58.5333 },
  "Ciudad Evita": { lat: -34.7167, lng: -58.5333 },
  "Villa Celina": { lat: -34.7, lng: -58.4667 },
  "Villa Insuperable": { lat: -34.6625, lng: -58.5342 },
  "20 de Junio": { lat: -34.8167, lng: -58.7333 },
};

/** Centro del partido: adonde mira el mapa cuando no hay nada seleccionado. */
export const CENTRO_MATANZA = { lat: -34.71, lng: -58.58 };

export const PAPELERAS_MATANZA: SemillaProspecto[] = [
  // ── San Justo ───────────────────────────────────────────────────────────
  {
    id: "batipel-san-justo",
    comercio: "Papelera Batipel S.R.L.",
    localidad: "San Justo",
    direccion: "Av. Pres. Dr. Arturo Umberto Illia 1856",
    telefono: "011 4441-8686",
    whatsapp: "",
    email: "papelera_batipel@yahoo.com.ar",
    web: "https://batipel.com",
    instagram: "",
    facebook: "https://www.facebook.com/p/Papelera-Batipel-100063531010628/",
    horario: "",
    notas: "Artículos para embalaje. CUIT 30-71024793-1. CP 1754.",
    fuente: "Páginas Amarillas / Firmania / Cuit Online",
  },
  {
    id: "plastipel-san-justo",
    comercio: "Papelera Plastipel",
    localidad: "San Justo",
    direccion: "Av. Monseñor Bufano 2750 (ex Camino de Cintura)",
    telefono: "011 15-6605-8150",
    whatsapp: "",
    email: "",
    web: "https://www.papeleraplastipel.com.ar",
    instagram: "https://www.instagram.com/papeleraplastipel/",
    facebook: "https://www.facebook.com/papeleraplastipel/",
    horario: "Lun a vie 9 a 17 · Sáb 9 a 13",
    notas: "Tiene sitio propio con formulario de contacto.",
    fuente: "Sitio propio / Cylex",
  },
  {
    id: "plastex-san-justo",
    comercio: "Papelera Plastex",
    localidad: "San Justo",
    direccion: "Av. Juan Manuel de Rosas 3554",
    telefono: "011 6068-2540",
    whatsapp: "11 2586-4651",
    email: "",
    web: "",
    instagram: "https://www.instagram.com/papelera.plastex/",
    facebook: "",
    horario: "Lun a vie 8:30 a 17 · Sáb 8:30 a 13",
    notas:
      "Descartables, bolsas y papeles. Algunos directorios la listan en el 3556: es la misma cuadra, confirmar al pasar.",
    fuente: "argentino.com.ar / Instagram propio",
  },
  {
    id: "cuyen-san-justo",
    comercio: "Papelera Cuyen",
    localidad: "San Justo",
    direccion: "Av. Monseñor Bufano 2819",
    telefono: "011 4484-0565",
    whatsapp: "",
    email: "",
    web: "https://papeleracuyen.com.ar",
    instagram: "https://www.instagram.com/papeleracuyen/",
    facebook: "",
    horario: "Lun a vie 9 a 13 y 13:30 a 17 · Sáb 9 a 17",
    notas: "Mayorista y minorista, negocio familiar. Está a media cuadra de Plastipel.",
    fuente: "Sitio propio / Páginas Amarillas",
  },
  {
    id: "donofrio-san-justo",
    comercio: "Papelera Donofrio",
    localidad: "San Justo",
    direccion: "Cerviño 3798",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "https://www.instagram.com/donofriopapelera/",
    facebook: "",
    horario: "",
    notas:
      "Bolsas, camisetas, vasos, bandejas, cartón y papeles. El directorio publica un teléfono incompleto: pedirlo por Instagram.",
    fuente: "argentino.com.ar / Instagram propio",
  },
  {
    id: "papeleros-san-justo",
    comercio: "Papeleros",
    localidad: "San Justo",
    direccion: "Tte. Gral. J. D. Perón 3593 (esq. Paraguay)",
    telefono: "011 4651-7848",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "",
    facebook: "",
    horario: "",
    notas: "",
    fuente: "sanjustolamatanza.com.ar",
  },

  // ── Ramos Mejía ─────────────────────────────────────────────────────────
  {
    id: "maluay-ramos-mejia",
    comercio: "Papelera Maluay S.R.L.",
    localidad: "Ramos Mejía",
    direccion: "Av. Rivadavia 13062",
    telefono: "011 3480-6892",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "https://www.instagram.com/papeleramaluay/",
    facebook: "https://www.facebook.com/papeleramaluay/",
    horario: "",
    notas: "CUIT 33-71572018-9. CP B1704.",
    fuente: "Firmania / Cylex / Cuit Online",
  },
  {
    id: "triunvirato-ramos-mejia",
    comercio: "Papelera Triunvirato",
    localidad: "Ramos Mejía",
    direccion: "Bolívar 35",
    telefono: "011 4654-0632",
    whatsapp: "",
    email: "",
    web: "https://www.papeleratriunvirato.com.ar",
    instagram: "https://www.instagram.com/papeleratriunvirato/",
    facebook: "https://www.facebook.com/paptriunvirato/",
    horario: "",
    notas: "Distribuidora mayorista de bolsas de polietileno, rollos de arranque y embalaje.",
    fuente: "argentinafirm.com / Cylex / redes propias",
  },
  {
    id: "papelera-rm-ramos-mejia",
    comercio: "Papelera RM",
    localidad: "Ramos Mejía",
    direccion: "Av. San Martín 70",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "https://papelerarm.com",
    instagram: "https://www.instagram.com/papelerarm/",
    facebook: "https://www.facebook.com/papelerarm/",
    horario: "",
    notas:
      "Más de 30 años, por mayor y por menor. Apuntan a comercios gastronómicos: buen perfil para la línea de limpieza.",
    fuente: "Sitio propio / Cuit Online (30-71795597-4)",
  },

  // ── Lomas del Mirador ───────────────────────────────────────────────────
  {
    id: "bustamante-lomas-del-mirador",
    comercio: "Papelera Bustamante",
    localidad: "Lomas del Mirador",
    direccion: "Av. Juan Manuel de Rosas 773",
    telefono: "011 4699-1786 / 011 4699-1442",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "",
    facebook: "https://www.facebook.com/papeleralibreriabustamante/",
    horario: "",
    notas: "Papelera, librería y cotillón. Embalaje y librería comercial, con envíos a todo el país.",
    fuente: "Páginas Amarillas / argentino.com.ar",
  },
  {
    id: "bahia-lomas-del-mirador",
    comercio: "Papelera Bahía S.A.",
    localidad: "Lomas del Mirador",
    direccion: "Charcas 3896",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "",
    facebook: "",
    horario: "",
    notas: "CUIT 30-71191156-8. Sin teléfono publicado: es visita a puerta fría.",
    fuente: "Cuit Online / cercanooeste.com",
  },

  // ── Villa Madero ────────────────────────────────────────────────────────
  {
    id: "araujo-villa-madero",
    comercio: "Papelera Araujo",
    localidad: "Villa Madero",
    direccion: "Av. Vélez Sarsfield 36",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "",
    facebook: "",
    horario: "",
    notas: "Papelera, cotillón, repostería y decoración.",
    fuente: "Páginas Amarillas / cercanooeste.com",
  },
  {
    id: "yajulu-villa-madero",
    comercio: "Papelera Yajulu",
    localidad: "Villa Madero",
    direccion: "Av. Crovara 846",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "https://www.instagram.com/mipapelerayajulu/",
    facebook: "",
    horario: "",
    notas: "Descartables, embalaje, cotillón y librería.",
    fuente: "lazonaoeste.com / Instagram propio",
  },
  {
    id: "madero-villa-madero",
    comercio: "Papelera Madero",
    localidad: "Villa Madero",
    direccion: "",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "",
    facebook: "",
    horario: "",
    notas: "Figura en el directorio de la zona pero sin dirección ni teléfono publicados: hay que ubicarla.",
    fuente: "cercanooeste.com",
  },
  {
    id: "san-martin-villa-madero",
    comercio: "Papelera San Martín",
    localidad: "Villa Madero",
    direccion: "",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "",
    facebook: "",
    horario: "",
    notas: "Listada en el rubro embalajes, sin datos de contacto publicados.",
    fuente: "cercanooeste.com",
  },

  // ── La Tablada ──────────────────────────────────────────────────────────
  {
    id: "loly-la-tablada",
    comercio: "Papelera Loly",
    localidad: "La Tablada",
    direccion: "Av. Intendente Esteban Crovara 315",
    telefono: "011 4652-1826",
    whatsapp: "11 3568-4463",
    email: "",
    web: "",
    instagram: "",
    facebook: "",
    horario: "Lun a vie 9 a 14 y 15 a 19 · Sáb 9 a 13",
    notas: "",
    fuente: "near-place.com / findglocal.com",
  },
  {
    id: "matanza-embalajes-la-tablada",
    comercio: "Matanza Embalajes (La Tablada)",
    localidad: "La Tablada",
    direccion: "",
    telefono: "011 4694-1587",
    whatsapp: "",
    email: "matanzaIC@hotmail.com.ar",
    web: "https://matanzaembalajes.wix.com/misitio",
    instagram: "https://www.instagram.com/matanzaembalajes/",
    facebook: "https://www.facebook.com/matanza.embalajes/",
    horario: "",
    notas:
      "Tiene dos locales, este y el de Casanova. El teléfono y el mail publicados son los mismos para ambos: confirmar cuál corresponde a cada puerta.",
    fuente: "cercanooeste.com / redes propias",
  },

  // ── Isidro Casanova ─────────────────────────────────────────────────────
  {
    id: "matanza-embalajes-casanova",
    comercio: "Matanza Embalajes (Isidro Casanova)",
    localidad: "Isidro Casanova",
    direccion: "",
    telefono: "011 4694-1587",
    whatsapp: "",
    email: "matanzaIC@hotmail.com.ar",
    web: "https://matanzaembalajes.wix.com/misitio",
    instagram: "https://www.instagram.com/matanzaembalajes/",
    facebook: "https://www.facebook.com/p/Matanza-Embalajes-100067208640606/",
    horario: "",
    notas: "Embalaje e insumos para industria y comercio, incluidos descartables.",
    fuente: "cercanooeste.com / redes propias",
  },
  {
    id: "ruta-3-casanova",
    comercio: "Papelera Ruta 3",
    localidad: "Isidro Casanova",
    direccion: "Av. Juan Manuel de Rosas 6836",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "",
    facebook: "",
    horario: "",
    notas: "El directorio publica el teléfono cortado (011 4486-00..): pedirlo en el local.",
    fuente: "argentino.com.ar",
  },
  {
    id: "cristiania-casanova",
    comercio: "Papelera y Cotillón Cristiania",
    localidad: "Isidro Casanova",
    direccion: "Av. Cristianía 1867",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "",
    facebook: "https://www.facebook.com/papeleracristiania/",
    horario: "",
    notas: "Descartables e insumos para comercio y hogar.",
    fuente: "Facebook propio / argentino.com.ar",
  },
  {
    id: "ke-papelon-casanova",
    comercio: "Ke Papelón",
    localidad: "Isidro Casanova",
    direccion: "",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "",
    facebook: "",
    horario: "",
    notas: "Cotillón, embalajes, bobinas, cajas y descartables. Falta la dirección exacta.",
    fuente: "lazonaoeste.com",
  },

  // ── Villa Luzuriaga ─────────────────────────────────────────────────────
  {
    id: "amichi-villa-luzuriaga",
    comercio: "Papelera Amichi",
    localidad: "Villa Luzuriaga",
    direccion: "Av. Don Bosco 2542",
    telefono: "011 3436-0926",
    whatsapp: "11 3290-7503",
    email: "papeleraamichi@gmail.com",
    web: "",
    instagram: "https://www.instagram.com/papeleraamichi/",
    facebook: "https://www.facebook.com/p/Papelera-Amichi-100029381353252/",
    horario: "Lun a vie 8:30 a 19 · Sáb 8:30 a 13",
    notas: "La ficha más completa del relevamiento: teléfono, WhatsApp y mail publicados.",
    fuente: "todosnegocios.com / redes propias",
  },
  {
    id: "hyper-papelera-villa-luzuriaga",
    comercio: "Hyper Papelera",
    localidad: "Villa Luzuriaga",
    direccion: "",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "",
    facebook: "https://www.facebook.com/p/Hyper-Papelera-100083799381701/",
    horario: "",
    notas: "Solo aparece la página de Facebook: escribir por ahí para conseguir dirección y teléfono.",
    fuente: "Facebook propio",
  },
  {
    id: "bolsas-luzuriaga",
    comercio: "Bolsas Luzuriaga",
    localidad: "Villa Luzuriaga",
    direccion: "",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "https://bolsasluzuriaga.wixsite.com/bolsasluzuriaga",
    instagram: "",
    facebook: "",
    horario: "",
    notas: "Bolsas de polipropileno y polietileno por mayor y menor.",
    fuente: "Sitio propio",
  },

  // ── Rafael Castillo ─────────────────────────────────────────────────────
  {
    id: "la-balsa-rafael-castillo",
    comercio: "Papelera La Balsa",
    localidad: "Rafael Castillo",
    direccion: "Carlos Casares 765",
    telefono: "011 4486-0983",
    whatsapp: "",
    email: "",
    web: "http://www.papeleralabalsa.com.ar",
    instagram: "",
    facebook: "",
    horario: "",
    notas:
      "Bolsas, embalaje, descartables y librería comercial. También tiene local en Ciudadela, fuera del partido.",
    fuente: "Sitio propio / Páginas Amarillas",
  },

  // ── Gregorio de Laferrere ───────────────────────────────────────────────
  {
    id: "papelera-san-justo-laferrere",
    comercio: "Papelera San Justo (sucursal Laferrere)",
    localidad: "Gregorio de Laferrere",
    direccion: "Brig. Gral. Juan Manuel de Rosas 10085",
    telefono: "011 7114-5296",
    whatsapp: "",
    email: "",
    web: "https://www.papelerasanjusto.com.ar",
    instagram: "",
    facebook: "https://www.facebook.com/PapeleraSanjusto/",
    horario: "",
    notas:
      "Cadena con locales en San Justo, Laferrere y El Palomar, y tienda online. Distribuye marcas grandes: es competencia además de cliente posible.",
    fuente: "Sitio propio / Firmania",
  },
  {
    id: "papelera-laferrere",
    comercio: "Papelera Laferrere",
    localidad: "Gregorio de Laferrere",
    direccion: "Soberanía Nacional 3372",
    telefono: "11 6995-4687",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "https://www.instagram.com/papelera.laferrere/",
    facebook: "",
    horario: "Lun a vie 8 a 18 · Sáb 8 a 14",
    notas: "Librería, cotillón y descartables.",
    fuente: "argentino.com.ar / Instagram propio",
  },
  {
    id: "caromar-laferrere",
    comercio: "Caromar",
    localidad: "Gregorio de Laferrere",
    direccion: "",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "",
    facebook: "",
    horario: "",
    notas:
      "Listada como distribuidora mayorista de artículos de limpieza, no como papelera: es el rubro exacto de Aqua Mar.",
    fuente: "cercanooeste.com",
  },

  // ── González Catán ──────────────────────────────────────────────────────
  {
    id: "alberto-gonzalez-catan",
    comercio: "Papelera y Cotillón Alberto",
    localidad: "González Catán",
    direccion: "Brig. Gral. Juan Manuel de Rosas 19573",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "",
    facebook: "https://www.facebook.com/papeleraycotillonalberto35/",
    horario: "",
    notas: "30 años en la zona, por mayor y menor. Sin teléfono publicado.",
    fuente: "Facebook propio",
  },

  // ── Virrey del Pino ─────────────────────────────────────────────────────
  {
    id: "la-esperanza-virrey-del-pino",
    comercio: "Cotillón y Papelera La Esperanza",
    localidad: "Virrey del Pino",
    direccion: "Hugo Wast 1092",
    telefono: "",
    whatsapp: "",
    email: "",
    web: "",
    instagram: "https://www.instagram.com/cotillonypapeleralaesperanza/",
    facebook: "",
    horario: "Lun a sáb 9 a 13 y 16:30 a 20:30",
    notas: "Papelera, cotillón y repostería, por mayor y menor.",
    fuente: "Instagram propio",
  },
];
