// Generado desde docs/comercial/prospectos.py — no editar a mano.
// Para cambiar los datos base se edita ese archivo y se corre
//   python3 docs/comercial/exportar-ts.py
// Los negocios que el equipo carga desde la app viven en la base, no acá.

export type Prospecto = {
  id: string; nombre: string; rubro: string; localidad: string;
  instagram: string; facebook: string; web: string; direccion: string;
  telefono: string; mail: string; seguidores: string; contenido: string;
  fuente: string; ver: "ok" | "parcial" | "nombre"; prioridad: string; cerca: string;
};

export const ESTUDIO = {
  "nombre": "Nexo Studios",
  "direccion": "Hipólito Yrigoyen 4716, Villa Lynch, General San Martín",
  "mapa": "https://www.google.com/maps/search/Hip%C3%B3lito+Yrigoyen+4716+Villa+Lynch+General+San+Mart%C3%ADn"
};

export const PROSPECTOS: Prospecto[] = [
  {
    "nombre": "Berlina Ballester",
    "rubro": "Cervecería",
    "localidad": "Villa Ballester",
    "instagram": "berlinaballester",
    "facebook": "BerlinaBallester",
    "web": "",
    "direccion": "Lacroze 5031, Villa Ballester",
    "telefono": "+54 11 3252-9290",
    "mail": "berlinaballesterbrewery@gmail.com",
    "seguidores": "~20.000",
    "contenido": "Cervecería, bar y resto. Abre todos los días desde las 18 h. Cuenta activa y con volumen de seguidores alto para la zona: es de las marcas locales con mejor producción de contenido.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "ok",
    "prioridad": "alta",
    "cerca": "",
    "id": "berlina-ballester"
  },
  {
    "nombre": "Cerveza Zombiecat",
    "rubro": "Cervecería",
    "localidad": "Villa Ballester",
    "instagram": "cerveza.zombiecat",
    "facebook": "",
    "web": "",
    "direccion": "Libertad 5183, Villa Ballester",
    "telefono": "11 2393-1955",
    "mail": "",
    "seguidores": "~18.000",
    "contenido": "Brewpub con quince canillas rotativas: cerveza propia y de invitados, elaborada a la vista. Dom a jue de 18 a 00, vie y sáb hasta la 1. Figura como Zombie Cat Microcervecería. Aparece un segundo teléfono, 011 3402-2388: probar primero el 2393-1955, que es el que viene con la dirección.hasta la 1. Marca con identidad propia y producto que se muestra bien en cámara: encaja con el live set.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "ok",
    "prioridad": "alta",
    "cerca": "",
    "id": "cerveza-zombiecat"
  },
  {
    "nombre": "Cervelar Villa Ballester",
    "rubro": "Cervecería",
    "localidad": "Villa Ballester",
    "instagram": "cervelarvillaballester",
    "facebook": "cervelarvillaballester",
    "web": "https://villaballester.cervelar.com.ar",
    "direccion": "Lamadrid 2547, Villa Ballester",
    "telefono": "011 5827-0791",
    "mail": "",
    "seguidores": "",
    "contenido": "Cervecería informal: canillas, coctelería, picadas, hamburguesas y comida mexicana. Dom a jue de 18 a 1, vie y sáb hasta las 2, happy hour de 18 a 20. Tiene sitio propio de la sucursal.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "ok",
    "prioridad": "alta",
    "cerca": "",
    "id": "cervelar-villa-ballester"
  },
  {
    "nombre": "El Patio de la Cerveza — Irish Pub",
    "rubro": "Cervecería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "elpatiodelacervezairishpub",
    "web": "",
    "direccion": "Boulevard Ballester 5231, Villa Ballester",
    "telefono": "+54 11 7398-4848",
    "mail": "elpatiodelacervezairishpub@gmail.com",
    "seguidores": "",
    "contenido": "Bar con cerveza artesanal tirada y tablas de fiambres. Tiene mail propio publicado, así que la propuesta se puede mandar sin pasar por el local.",
    "fuente": "Búsqueda web · página de Facebook",
    "ver": "ok",
    "prioridad": "media",
    "cerca": "",
    "id": "el-patio-de-la-cerveza-irish-pub"
  },
  {
    "nombre": "Varvarco Ballester",
    "rubro": "Cervecería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "varvarcoballester",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · página de Facebook",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "",
    "id": "varvarco-ballester"
  },
  {
    "nombre": "La Dionisia",
    "rubro": "Parrilla",
    "localidad": "Villa Ballester",
    "instagram": "ladionisia__",
    "facebook": "",
    "web": "",
    "direccion": "Lacroze 5074, Villa Ballester",
    "telefono": "011 2268-3892",
    "mail": "",
    "seguidores": "",
    "contenido": "Parrilla, restaurante y cafetería, fuerte en pastas caseras. Está a media cuadra de Berlina: la misma recorrida sirve para las dos.la misma recorrida sirve para las dos.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "ok",
    "prioridad": "alta",
    "cerca": "",
    "id": "la-dionisia"
  },
  {
    "nombre": "Parrilla Lago di Garda",
    "rubro": "Parrilla",
    "localidad": "Villa Ballester",
    "instagram": "parrillalagodigarda",
    "facebook": "SarmientoYAlvear",
    "web": "",
    "direccion": "Alvear 2000 (Sarmiento y Alvear), Villa Ballester",
    "telefono": "+54 11 2673-8870",
    "mail": "",
    "seguidores": "",
    "contenido": "De martes a viernes, platos del día además del asado; sábados y domingos solo parrilla. Delivery y take away.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "ok",
    "prioridad": "media",
    "cerca": "",
    "id": "parrilla-lago-di-garda"
  },
  {
    "nombre": "La Estancia Ballester",
    "rubro": "Parrilla",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "laestanciaballesterok",
    "web": "",
    "direccion": "José Hernández 3176, Villa Ballester",
    "telefono": "4738-0135",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · página de Facebook",
    "ver": "ok",
    "prioridad": "media",
    "cerca": "",
    "id": "la-estancia-ballester"
  },
  {
    "nombre": "Pizzería Piccirillo",
    "rubro": "Pizzería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "pizzeriapiccirillo",
    "web": "https://www.pizzeriapiccirillo.com",
    "direccion": "Jujuy 95 esq. América, Villa Ballester",
    "telefono": "011 4768-1333",
    "mail": "",
    "seguidores": "",
    "contenido": "Pizzas y empanadas con delivery en Villa Ballester, San Andrés, Chilavert y San Martín. Lun a sáb de 12 a 15 y de 20 a 23; domingos y feriados solo de noche. Tiene sitio propio con página de contacto.El teléfono salió de su propia publicación: confirmarlo antes de llamar.",
    "fuente": "Búsqueda web · página de Facebook",
    "ver": "ok",
    "prioridad": "media",
    "cerca": "",
    "id": "pizzeria-piccirillo"
  },
  {
    "nombre": "Las Delicias Ballester",
    "rubro": "Panadería",
    "localidad": "Villa Ballester",
    "instagram": "lasdelicias.ballester",
    "facebook": "",
    "web": "",
    "direccion": "Congreso 4168, Villa Ballester",
    "telefono": "4768-2219",
    "mail": "",
    "seguidores": "",
    "contenido": "Panadería y confitería con envío a domicilio sin cargo, estacionamiento propio y terraza. Figura primera entre las panaderías de San Martín. OJO: aparecen tres cuentas parecidas —@lasdelicias.ballester, @lasdeliciaspc y @panaderialasdelicias8—. Confirmar cuál es la de este local antes de escribir por Instagram.propia y publica producto: el rubro más fácil de mostrar al aire.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "ok",
    "prioridad": "alta",
    "cerca": "",
    "id": "las-delicias-ballester"
  },
  {
    "nombre": "Panadería El Molino",
    "rubro": "Panadería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "PanaderiaElMolino",
    "web": "",
    "direccion": "Almte. Brown 2961, Villa Ballester",
    "telefono": "011 6003-1435",
    "mail": "panaderiaelmolino.vb@gmail.com",
    "seguidores": "",
    "contenido": "Panadería, confitería y cafetería. Lun a sáb de 6 a 21, domingos de 7 a 21. Tiene mail propio publicado.",
    "fuente": "Búsqueda web · página de Facebook",
    "ver": "ok",
    "prioridad": "media",
    "cerca": "",
    "id": "panaderia-el-molino"
  },
  {
    "nombre": "Panadería 25 de Mayo",
    "rubro": "Panadería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Abierta las 24 horas.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "panaderia-25-de-mayo"
  },
  {
    "nombre": "Catuli Pastelería",
    "rubro": "Panadería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Tortas de cumpleaños.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "catuli-pasteleria"
  },
  {
    "nombre": "La Nueva Panecillos",
    "rubro": "Panadería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Facturas y tortas.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "la-nueva-panecillos"
  },
  {
    "nombre": "Panadería Don Luis",
    "rubro": "Panadería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Pan artesanal.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "panaderia-don-luis"
  },
  {
    "nombre": "La Pana de Rodríguez",
    "rubro": "Panadería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Chipas.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "la-pana-de-rodriguez"
  },
  {
    "nombre": "Tutto e Pane",
    "rubro": "Panadería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "tutto-e-pane"
  },
  {
    "nombre": "Panadería San Francisco",
    "rubro": "Panadería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Facturas y medialunas.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "panaderia-san-francisco"
  },
  {
    "nombre": "Tartas Artesanales Silvia",
    "rubro": "Panadería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Tartas caseras.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "tartas-artesanales-silvia"
  },
  {
    "nombre": "Heladerías Chinin",
    "rubro": "Heladería",
    "localidad": "San Martín",
    "instagram": "chininhelados",
    "facebook": "chininhelados",
    "web": "https://www.chinin.com.ar/contacto",
    "direccion": "Pueyrredón 4316, San Martín · Alvear 2210, Villa Ballester",
    "telefono": "11 3168-4141 (San Martín) · 11 4755-4964 (Ballester)",
    "mail": "",
    "seguidores": "",
    "contenido": "Helado artesanal desde 1965, con locales en San Martín, Villa Ballester y Núñez. El sitio tiene formulario de contacto. Por tener tres sucursales y sesenta años de marca, da para una acción de temporada y no una mención suelta: es de las más grandes de la lista.Toma pedidos online y por WhatsApp. Al tener más de un local, da para una acción de temporada y no una mención suelta.",
    "fuente": "Búsqueda web · página de Facebook",
    "ver": "ok",
    "prioridad": "alta",
    "cerca": "",
    "id": "heladerias-chinin"
  },
  {
    "nombre": "Heladería CR Villa Ballester",
    "rubro": "Heladería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "https://crhelados.com",
    "direccion": "Pacífico Rodríguez 4749, Villa Ballester",
    "telefono": "+54 11 4768-5650",
    "mail": "",
    "seguidores": "",
    "contenido": "Heladería artesanal abierta de 11 a 1 de la mañana, todos los días, con delivery los 365. Tiene linktree propio (crhelados_Ballester).",
    "fuente": "Búsqueda web · directorio local",
    "ver": "ok",
    "prioridad": "media",
    "cerca": "",
    "id": "heladeria-cr-villa-ballester"
  },
  {
    "nombre": "Heladería San Martín",
    "rubro": "Heladería",
    "localidad": "San Martín",
    "instagram": "san_martin_gelato_artesanal",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Gelato artesanal.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "",
    "id": "heladeria-san-martin"
  },
  {
    "nombre": "Muscle Factory",
    "rubro": "Gimnasio",
    "localidad": "Villa Ballester",
    "instagram": "gimnasio.musclefactory",
    "facebook": "",
    "web": "",
    "direccion": "Lacroze 5068, Villa Ballester",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Gimnasio sobre Lacroze, en la misma cuadra que Berlina y La Dionisia. Lun a vie de 8 a 23, climatizado. Los dueños figuran en Instagram como @leonel_hagemann y @daiviloni.ifbbpro: ahí conviene escribir, porque no publica teléfono en ningún lado.Rubro con contenido propio constante y público fiel.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "ok",
    "prioridad": "alta",
    "cerca": "",
    "id": "muscle-factory"
  },
  {
    "nombre": "ObeliX Cross Training",
    "rubro": "Gimnasio",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Entrenamiento funcional / cross training.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "obelix-cross-training"
  },
  {
    "nombre": "Café Martínez San Martín",
    "rubro": "Café",
    "localidad": "San Martín",
    "instagram": "cafemartinezsanmartin",
    "facebook": "",
    "web": "",
    "direccion": "Bonifacini 2098, San Martín",
    "telefono": "11 4897-7869",
    "mail": "",
    "seguidores": "",
    "contenido": "Lun a vie de 7:30 a 21:30, sáb y dom desde las 8. Es sucursal de cadena: la decisión de sponsoreo puede depender de la franquicia y no del local. Confirmar quién decide antes de invertir tiempo comercial.franquicia y no del local. Confirmar quién decide antes de invertir tiempo comercial.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "ok",
    "prioridad": "media",
    "cerca": "",
    "id": "cafe-martinez-san-martin"
  },
  {
    "nombre": "Ballester Gastronomía",
    "rubro": "Medio local",
    "localidad": "Villa Ballester",
    "instagram": "ballestergastronomia",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "~12.000",
    "contenido": "Cuenta de gastronomía de Ballester y todo San Martín. No es un sponsor clásico: es un socio de difusión. Conviene tratarla como partner de medios y no venderle un paquete.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "ok",
    "prioridad": "alta",
    "cerca": "",
    "id": "ballester-gastronomia"
  },
  {
    "nombre": "La Tienda San Martín",
    "rubro": "Indumentaria",
    "localidad": "San Martín",
    "instagram": "",
    "facebook": "LaTiendaSanMartin",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · página de Facebook",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "",
    "id": "la-tienda-san-martin"
  },
  {
    "nombre": "Panadería y Confitería Roma",
    "rubro": "Panadería",
    "localidad": "Villa Lynch",
    "instagram": "",
    "facebook": "ROMASCONFITERIA",
    "web": "",
    "direccion": "Hipólito Yrigoyen 4598, Villa Lynch",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Abre de 6 a 21, los siete días, sin cerrar al mediodía. Reconocida en San Martín por los sándwiches de miga. Tiene delivery y take away. Es el negocio más cercano de toda la lista: se cruza la calle y se habla con el dueño.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "ok",
    "prioridad": "alta",
    "cerca": "A una cuadra del estudio",
    "id": "panaderia-y-confiteria-roma"
  },
  {
    "nombre": "Heladería Xelta",
    "rubro": "Heladería",
    "localidad": "Villa Lynch",
    "instagram": "",
    "facebook": "heladeriaxelta",
    "web": "",
    "direccion": "Perdriel 4902 esq. Saladillo, Villa Lynch",
    "telefono": "+54 11 4713-4565",
    "mail": "xeltaheladeria@hotmail.com",
    "seguidores": "",
    "contenido": "Mar a vie y domingos de 11:30 a 1:30, sábados hasta las 2. Mesas afuera y wifi. Tiene mail propio publicado, así que se le puede mandar la propuesta sin pasar por el local.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "ok",
    "prioridad": "alta",
    "cerca": "Zona del estudio",
    "id": "heladeria-xelta"
  },
  {
    "nombre": "Il Clementini",
    "rubro": "Pizzería",
    "localidad": "Villa Lynch",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "Perdriel 5301, Villa Lynch",
    "telefono": "+54 11 4712-7148",
    "mail": "",
    "seguidores": "",
    "contenido": "Pizza a la parrilla. Sobre Perdriel, la misma avenida que Xelta.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "parcial",
    "prioridad": "alta",
    "cerca": "Zona del estudio",
    "id": "il-clementini"
  },
  {
    "nombre": "Parrilla El Bodegón",
    "rubro": "Parrilla",
    "localidad": "Villa Lynch",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "Av. Iturraspe 1489, Villa Lynch",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · directorio local",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "Zona del estudio",
    "id": "parrilla-el-bodegon"
  },
  {
    "nombre": "Saccotex",
    "rubro": "Servicios",
    "localidad": "Villa Lynch",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "Hipólito Yrigoyen 4445, Villa Lynch",
    "telefono": "+54 11 4713-7169 · +54 11 4713-7181",
    "mail": "",
    "seguidores": "",
    "contenido": "Empresa sobre la misma calle del estudio. Villa Lynch es zona textil, así que probablemente sea del rubro: confirmar si es marca de consumo o proveedor industrial antes de ofrecerle sponsoreo de programa.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "Sobre Yrigoyen, a pocas cuadras",
    "id": "saccotex"
  },
  {
    "nombre": "Delicias Caseras",
    "rubro": "Rotisería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Aparece primera en los directorios de rotisería y comidas para llevar de Ballester. Rubro sin nadie cargado todavía: conviene abrirlo con la más fuerte.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "alta",
    "cerca": "",
    "id": "delicias-caseras"
  },
  {
    "nombre": "Parrilla y Rotisería Alvear",
    "rubro": "Rotisería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "Alvear 661, Villa Ballester",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · directorio local",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "",
    "id": "parrilla-y-rotiseria-alvear"
  },
  {
    "nombre": "Como Reyes Delivery",
    "rubro": "Rotisería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "como-reyes-delivery"
  },
  {
    "nombre": "Bouquet Garni Recetas",
    "rubro": "Rotisería",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Viandas y comidas preparadas.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "bouquet-garni-recetas"
  },
  {
    "nombre": "Todo Casero — Rotisería",
    "rubro": "Rotisería",
    "localidad": "José León Suárez",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "Sarratea 9300, José León Suárez",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Segunda entrada a José León Suárez, que estaba casi sin cubrir.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "",
    "id": "todo-casero-rotiseria"
  },
  {
    "nombre": "Distribuidora de bebidas — Savio 2750",
    "rubro": "Distribuidora",
    "localidad": "San Martín",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "Savio 2750, San Martín",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "El directorio la lista por dirección, sin nombre de fantasía. Hay que pasar y preguntar cómo se llama y quién decide.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "alta",
    "cerca": "",
    "id": "distribuidora-de-bebidas-savio-2750"
  },
  {
    "nombre": "Distribuidora de bebidas — Balbín 2822",
    "rubro": "Distribuidora",
    "localidad": "Billinghurst",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "Av. Dr. Ricardo Balbín 2822, Billinghurst",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Misma situación: dirección sin nombre. Primera entrada a Billinghurst.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "distribuidora-de-bebidas-balbin-2822"
  },
  {
    "nombre": "Distribuidora San Martín",
    "rubro": "Distribuidora",
    "localidad": "Villa Lynch",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "Gral. Hornos 836, Villa Lynch",
    "telefono": "+54 11 4712-1999",
    "mail": "",
    "seguidores": "",
    "contenido": "Mayorista: vende por pallet y pack cerrado —aguas, cervezas, gaseosas—. Por volumen es la que mejor puede bancar un canje grande, y encima está en la zona del estudio.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "ok",
    "prioridad": "alta",
    "cerca": "Zona del estudio",
    "id": "distribuidora-san-martin"
  },
  {
    "nombre": "Fuego",
    "rubro": "Estética",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "Boulevard Ballester, Villa Ballester",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Centro de estética atendido por mujeres trans, con cobertura en medios nacionales. Peluquería, barbería y uñas. Tiene una historia propia fuerte: encaja mejor como invitada de un programa que como PNT.",
    "fuente": "Nota de Infobae",
    "ver": "parcial",
    "prioridad": "alta",
    "cerca": "",
    "id": "fuego"
  },
  {
    "nombre": "Barbería San Martín",
    "rubro": "Estética",
    "localidad": "San Martín",
    "instagram": "barberiasanmartin",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "~585",
    "contenido": "Barbería clásica mezclada con estilos actuales. Cuenta chica pero activa.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "ok",
    "prioridad": "media",
    "cerca": "",
    "id": "barberia-san-martin"
  },
  {
    "nombre": "Barber San Andrés",
    "rubro": "Estética",
    "localidad": "San Andrés",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Corte y barba. Primera entrada a San Andrés.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "barber-san-andres"
  },
  {
    "nombre": "Gringo Barbería",
    "rubro": "Estética",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "gringo-barberia"
  },
  {
    "nombre": "Franco Peluquería",
    "rubro": "Estética",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "franco-peluqueria"
  },
  {
    "nombre": "We Love Hair",
    "rubro": "Estética",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · directorio local",
    "ver": "nombre",
    "prioridad": "media",
    "cerca": "",
    "id": "we-love-hair"
  },
  {
    "nombre": "Centro Médico Vet Suárez",
    "rubro": "Servicios",
    "localidad": "José León Suárez",
    "instagram": "cmvetesuarez",
    "facebook": "",
    "web": "",
    "direccion": "Independencia 7181, José León Suárez",
    "telefono": "4722-0965",
    "mail": "",
    "seguidores": "",
    "contenido": "Clínica, cirugía, radiología, especialistas, farmacia, pet shop y peluquería canina. Lun a sáb de 9 a 12:30 y de 16 a 19:30. El teléfono es también WhatsApp. Primera entrada a José León Suárez.canina. Servicio completo y con cuenta propia: primera entrada a José León Suárez y rubro con público muy fiel.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "ok",
    "prioridad": "alta",
    "cerca": "",
    "id": "centro-medico-vet-suarez"
  },
  {
    "nombre": "Clínica Veterinaria San Martín",
    "rubro": "Servicios",
    "localidad": "San Martín",
    "instagram": "clinicaveterinariasanmartin",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "",
    "id": "clinica-veterinaria-san-martin"
  },
  {
    "nombre": "Hospital Veterinario San Martín",
    "rubro": "Servicios",
    "localidad": "San Martín",
    "instagram": "clinicaveterinaria_sanmartin",
    "facebook": "",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "",
    "id": "hospital-veterinario-san-martin"
  },
  {
    "nombre": "EVN Veterinarias",
    "rubro": "Servicios",
    "localidad": "José León Suárez",
    "instagram": "",
    "facebook": "evn.veterinarias",
    "web": "",
    "direccion": "Diagonal José León Suárez 7143",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · página de Facebook",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "",
    "id": "evn-veterinarias"
  },
  {
    "nombre": "Pet Shop y Veterinaria Natural Life",
    "rubro": "Servicios",
    "localidad": "Villa Ballester",
    "instagram": "",
    "facebook": "",
    "web": "https://natural-life.com.ar",
    "direccion": "Roca 3100 esq. Artigas, Villa Ballester",
    "telefono": "11 5400-4084 · 0810-999-6288",
    "mail": "",
    "seguidores": "",
    "contenido": "Pet shop grande y veterinaria en una esquina muy visible. Lun a sáb de 9 a 13 y de 16 a 20.",
    "fuente": "Búsqueda web · directorio local",
    "ver": "ok",
    "prioridad": "media",
    "cerca": "",
    "id": "pet-shop-y-veterinaria-natural-life"
  },
  {
    "nombre": "Lubricentro San Martín",
    "rubro": "Servicios",
    "localidad": "San Martín",
    "instagram": "lubrimosconi",
    "facebook": "Lubrisanmartin",
    "web": "",
    "direccion": "Av. Mosconi 2949",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Lubricentro y taller mecánico. Confirmar que la dirección de Mosconi sea la de San Martín y no la homónima de Capital antes de salir.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "",
    "id": "lubricentro-san-martin"
  },
  {
    "nombre": "GP Lubricentro",
    "rubro": "Servicios",
    "localidad": "San Martín",
    "instagram": "",
    "facebook": "GPSERVICEINTEGRAL",
    "web": "",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Búsqueda web · página de Facebook",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "",
    "id": "gp-lubricentro"
  },
  {
    "nombre": "Tienda de Sabores Villa Ballester",
    "rubro": "Servicios",
    "localidad": "Villa Ballester",
    "instagram": "tienda_desaboresballester",
    "facebook": "tiendadesaboressm",
    "web": "",
    "direccion": "Lamadrid 1939, Villa Ballester",
    "telefono": "011 3002-5859",
    "mail": "",
    "seguidores": "",
    "contenido": "Carnicería, fiambrería y despensa en un mismo local, con venta por WhatsApp al mismo número y delivery. Lun a sáb de 9 a 20:30. Ya publica contenido de producto apuntado a la parrilla: es el perfil exacto de la propuesta.apuntadas a la parrilla. Es el perfil exacto que la propuesta describe: hace contenido y le falta nivel.",
    "fuente": "Búsqueda web · perfil de Instagram",
    "ver": "ok",
    "prioridad": "alta",
    "cerca": "",
    "id": "tienda-de-sabores-villa-ballester"
  },
  {
    "nombre": "Que Pasa Web",
    "rubro": "Medio local",
    "localidad": "San Martín",
    "instagram": "",
    "facebook": "",
    "web": "https://www.quepasaweb.com.ar",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "Portal de noticias de San Martín, con secciones por localidad. Cubre ferias, polos gastronómicos y comercios: sirve para canje de difusión y como fuente para encontrar negocios nuevos todas las semanas.",
    "fuente": "Sitio propio",
    "ver": "parcial",
    "prioridad": "alta",
    "cerca": "",
    "id": "que-pasa-web"
  },
  {
    "nombre": "Reflejos de la Ciudad",
    "rubro": "Medio local",
    "localidad": "San Martín",
    "instagram": "",
    "facebook": "",
    "web": "https://www.reflejosdelaciudad.com.ar",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Sitio propio",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "",
    "id": "reflejos-de-la-ciudad"
  },
  {
    "nombre": "SN Online — Servicio de Noticias",
    "rubro": "Medio local",
    "localidad": "San Martín",
    "instagram": "",
    "facebook": "",
    "web": "https://www.snonline.com.ar/san-martin",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Sitio propio",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "",
    "id": "sn-online-servicio-de-noticias"
  },
  {
    "nombre": "SM Noticias",
    "rubro": "Medio local",
    "localidad": "San Martín",
    "instagram": "",
    "facebook": "",
    "web": "https://www.smnoticias.com/distrito/sanmartin",
    "direccion": "",
    "telefono": "",
    "mail": "",
    "seguidores": "",
    "contenido": "",
    "fuente": "Sitio propio",
    "ver": "parcial",
    "prioridad": "media",
    "cerca": "",
    "id": "sm-noticias"
  }
];

export const ESTADOS = [
  {
    "k": "nuevo",
    "n": "Sin contactar",
    "c": "#7A8698"
  },
  {
    "k": "contactado",
    "n": "Contactado",
    "c": "#4DA3FF"
  },
  {
    "k": "reunion",
    "n": "Reunión",
    "c": "#C7A45E"
  },
  {
    "k": "propuesta",
    "n": "Propuesta",
    "c": "#2FC4E8"
  },
  {
    "k": "cerrado",
    "n": "Cerrado",
    "c": "#50D000"
  },
  {
    "k": "descartado",
    "n": "Descartado",
    "c": "#FF3F4D"
  }
] as const;

export const PERSONAS = [
  "Benja",
  "Juli",
  "Fede",
  "Nico"
] as const;

export const EQUIPO = [
  "Sin asignar",
  "Benja",
  "Juli",
  "Fede",
  "Nico"
] as const;

export const CANTERA = [
  {
    "q": "Rotisería",
    "e": "5 cargadas, casi sin contactos",
    "n": 4
  },
  {
    "q": "Distribuidora de bebidas",
    "e": "3 cargadas, todas sin nombre",
    "n": 4
  },
  {
    "q": "Food truck",
    "e": "Ninguno cargado: salen de las ferias",
    "n": 4
  },
  {
    "q": "Indumentaria",
    "e": "1 cargada",
    "n": 5
  },
  {
    "q": "San Andrés",
    "e": "1 negocio cargado",
    "n": 5
  },
  {
    "q": "Villa Lynch — zona del estudio",
    "e": "6 cargados: es la zona a exprimir",
    "n": 10
  },
  {
    "q": "Billinghurst",
    "e": "1 negocio cargado",
    "n": 4
  },
  {
    "q": "Villa Maipú y Sáenz Peña",
    "e": "Sin cobertura",
    "n": 5
  }
] as const;

export const CAZADEROS = [
  {
    "t": "La cuadra de Lacroze 5000",
    "d": "Berlina (5031), La Dionisia (5074) y Muscle Factory (5068) están a metros. Tres prospectos de prioridad alta en cincuenta metros, y alrededor está el corredor gastronómico entero.",
    "c": "Villa Ballester · cualquier día"
  },
  {
    "t": "Lavalle entre Lacroze y Boulevard",
    "d": "Es la zona de mayor movimiento comercial de Ballester, pegada a la estación. Una recorrida de dos cuadras da para una tarde de prospección.",
    "c": "Villa Ballester · horario comercial"
  },
  {
    "t": "Polo Gastronómico de Lacroze",
    "d": "Evento al aire libre con food trucks, feria de artesanos, música y pintura en vivo, armado alrededor de los emprendedores de la zona. Es donde están juntos todos los food trucks que no aparecen en ningún directorio.",
    "c": "Villa Ballester · por edición"
  },
  {
    "t": "Feria Sabores de Ballester",
    "d": "Ituzaingó y Capdevilla. Gastronomía argentina y de Brasil, Haití, España y México, con shows en vivo y artesanos. Puestos chicos, decisión rápida.",
    "c": "Villa Ballester · fin de semana"
  },
  {
    "t": "Expoclásicos Ballester",
    "d": "Autos clásicos, gastronomía y food trucks en el Liceo Militar General San Martín, San Lorenzo 3800. Evento solidario y con público familiar.",
    "c": "Villa Ballester · abril"
  },
  {
    "t": "Los medios locales, todas las semanas",
    "d": "Que Pasa Web, Reflejos de la Ciudad, SN Online y SM Noticias publican cada apertura, feria y movida comercial del partido. Es la fuente que se renueva sola: el negocio que sale en la nota hoy está buscando visibilidad hoy.",
    "c": "Todo el partido · semanal"
  }
] as const;

